### ISSUE TITLE
DHCPServer.Dispose throwing PlatformNotSupportedException in .NET Core application

### ISSUE THREAD

**Issue by mambrosius-mm** [dotnetprojects/sharp-dhcp-server-lib#10]
When calling DHCPServer.Dispose from a .NET Core application I am getting a PlatformNotSupportedException.
This is mentioned in the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread.abort?view=netframework-4.8#System_Threading_Thread_Abort).

System.PlatformNotSupportedException: Thread abort is not supported on this platform.
   at System.Threading.Thread.Abort()
   at DotNetProjects.DhcpServer.DHCPServer.Dispose()

**Comment by jogibear9988** [comment]
and how should this be fixed? could you create a pull req?

**Comment by mambrosius-mm** [comment]
Pull Request #11
